import './globals.css'
import Link from 'next/link'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-slate-800 text-white">
      <nav className="flex items-center justify-evenly text-2xl font-bold p-4 ">
        <Link href='/' className="">home</Link>
        <Link href='/feedback' className="">feedback</Link>
      </nav>
        {children}
        </body>
    </html>
  )
}
